### PR TITLE
Update build-all.ps1

### PR DESCRIPTION
**Pull request by hitaspdotnet**

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you for the first public PR of the new project :)

**Comment by hitaspdotnet** [comment]
@hikalkan Can I have PR in Modules category? I have modules in commerce scenario and contents management using abp 3.7 in ASP.NET ZERO template.
I can migrate them into vNext by using docs and samples

**Comment by hikalkan** [comment]
Hi,

ASP.NET Zero is a commerical project as you know. So, don't copy/paste code from there :)
For new modules, yes everyone can do it and it's very appreciated. Thanks.

**Comment by hitaspdotnet** [comment]
@hikalkan 
Hello Sir,
Yes, Sure 👍 
I'm start with Article Management (Topics/Pages and News) to make sure I'm on the right way.
Thanks in advance.

**Pull request merged**
