### PR TITLE
add Volo.Abp.EntityFrameworkCore.MySQL

### PR DESCRIPTION
**Pull request by jinghongbo**

### CODE REVIEW

**Comment by hikalkan** [comment]
Thanks a lot. I will review and merge it.

**Comment by LFeYls** [comment]
I have some problems when i try to use mysql.
I install Volo.Abp.EntityFrameworkCore.MySQL (Volo.Abp.EntityFrameworkCore.SqlServer has been uninstall)
Then I  modify these file:  
LionEntityFrameworkCoreModule.cs  :
//           typeof(AbpEntityFrameworkCoreSqlServerModule),
            typeof(AbpEntityFrameworkCoreMySQLModule),
appsettings.json:
"Default":"Server=localhost;Database=Lion;Uid=root;Password=123456;"
LionDbContextFactory.cs:
 public LionDbContext CreateDbContext(string[] args)
        {
            var configuration = BuildConfiguration();

//                  var builder = new DbContextOptionsBuilder<LionDbContext>()
//                         .UseSqlServer(configuration.GetConnectionString("Default"));
                     var builder = new DbContextOptionsBuilder<LionDbContext>()
                         .UseMySql(configuration.GetConnectionString("Default"));

            return new LionDbContext(builder.Options);
        }
LionWebModule.cs:
//            services.Configure<AbpDbContextOptions>(options => { options.UseSqlServer(); });
            services.Configure<AbpDbContextOptions>(options => options.UseMySQL());

but when i run 'dotnet ef migrations add Initalll', It doesn't work.
main exception message:
System.NotImplementedException: The 'MySQLBinaryTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider.

But if I replace Volo.Abp.EntityFrameworkCore.MySQL with Pomolo.EntityFrameworkCore.MySql 
I can add migrations and update database success, but it can not  run it.

Maybe I use it in a wrong way,can you give a simple example for it.
Thanks

**Comment by maliming** [comment]
I think it is better to use https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by anntiz** [comment]
> 
> 
> I have some problems when i try to use mysql.
> I install Volo.Abp.EntityFrameworkCore.MySQL (Volo.Abp.EntityFrameworkCore.SqlServer has been uninstall)
> Then I modify these file:
> LionEntityFrameworkCoreModule.cs :
> // typeof(AbpEntityFrameworkCoreSqlServerModule),
> typeof(AbpEntityFrameworkCoreMySQLModule),
> appsettings.json:
> "Default":"Server=localhost;Database=Lion;Uid=root;Password=123456;"
> LionDbContextFactory.cs:
> public LionDbContext CreateDbContext(string[] args)
> {
> var configuration = BuildConfiguration();
> 
> // var builder = new DbContextOptionsBuilder()
> // .UseSqlServer(configuration.GetConnectionString("Default"));
> var builder = new DbContextOptionsBuilder()
> .UseMySql(configuration.GetConnectionString("Default"));
> 
> ```
>         return new LionDbContext(builder.Options);
>     }
> ```
> 
> LionWebModule.cs:
> // services.Configure(options => { options.UseSqlServer(); });
> services.Configure(options => options.UseMySQL());
> 
> but when i run 'dotnet ef migrations add Initalll', It doesn't work.
> main exception message:
> System.NotImplementedException: The 'MySQLBinaryTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider.
> 
> But if I replace Volo.Abp.EntityFrameworkCore.MySQL with Pomolo.EntityFrameworkCore.MySql
> I can add migrations and update database success, but it can not run it.
> 
> Maybe I use it in a wrong way,can you give a simple example for it.
> Thanks

I have same problems

**Comment by LFeYls** [comment]
> > I have some problems when i try to use mysql.
> > I install Volo.Abp.EntityFrameworkCore.MySQL (Volo.Abp.EntityFrameworkCore.SqlServer has been uninstall)
> > Then I modify these file:
> > LionEntityFrameworkCoreModule.cs :
> > // typeof(AbpEntityFrameworkCoreSqlServerModule),
> > typeof(AbpEntityFrameworkCoreMySQLModule),
> > appsettings.json:
> > "Default":"Server=localhost;Database=Lion;Uid=root;Password=123456;"
> > LionDbContextFactory.cs:
> > public LionDbContext CreateDbContext(string[] args)
> > {
> > var configuration = BuildConfiguration();
> > // var builder = new DbContextOptionsBuilder()
> > // .UseSqlServer(configuration.GetConnectionString("Default"));
> > var builder = new DbContextOptionsBuilder()
> > .UseMySql(configuration.GetConnectionString("Default"));
> > ```
> >         return new LionDbContext(builder.Options);
> >     }
> > ```
> > LionWebModule.cs:
> > // services.Configure(options => { options.UseSqlServer(); });
> > services.Configure(options => options.UseMySQL());
> > but when i run 'dotnet ef migrations add Initalll', It doesn't work.
> > main exception message:
> > System.NotImplementedException: The 'MySQLBinaryTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider.
> > But if I replace Volo.Abp.EntityFrameworkCore.MySQL with Pomolo.EntityFrameworkCore.MySql
> > I can add migrations and update database success, but it can not run it.
> > Maybe I use it in a wrong way,can you give a simple example for it.
> > Thanks
> 
> I have same problems

你解决了没

**Comment by Eilyyyy** [comment]
i think pomelo is better.

**Pull request merged**
