### PR TITLE
 fixed blogging EF module namespace

### PR DESCRIPTION
**Pull request by hitaspdotnet**

### CODE REVIEW

**Comment by alirizaadiyahsi** [comment]
`using Volo.Blogging.EntityFrameworkCore.Volo.Blogging.EntityFrameworkCore` is correct. Did you try to build your project? It should failed.

**Comment by hitaspdotnet** [comment]
@alirizaadiyahsi Hi,
Why we need to use `Volo.Blogging.EntityFrameworkCore.Volo.Blogging.EntityFrameworkCore` as namespace for our EFCoreModule.cs ? When we changed the class namespace so this `Volo.Blogging.EntityFrameworkCore.Volo.Blogging.EntityFrameworkCore` namespace comes from where? Is it generated by ABP? 
I haven't build error. I'm on migrating my projects (modules) to vNext, please if I miss something on this guide me
Thanks

**Comment by hitaspdotnet** [comment]
Ok. Sorry. You right.

**Comment by hitaspdotnet** [comment]
I tried with VS, CLI and Rider, No build error. 
Class library default namespace is empty, why we need this 😭 
Other classes in same namespace have shorter namespace than EfModule.cs 

```
namespace Volo.Blogging.EntityFrameworkCore
{
    public static class BloggingDbContextModelBuilderExtensions
    {
```
Please check again @alirizaadiyahsi

**Pull request closed without merging**
